### ISSUE TITLE
Option to exclude letters from previous lessons

### ISSUE THREAD

**Issue by Afsar-Pasha** [simgunz/ktouch-lesson-generator#1]
Can you add a option to exclude letters from previous lessons?

**Comment by simgunz** [comment]
If you exclude letters from the previous lessons, all the lessons will be generated with random sequences of letters instead of meaningful words. It is well-known that this is a very bad way to learn touch typing. Is it there any specific reason why you would like to learn that way?

**Comment by Afsar-Pasha** [comment]
I want to generate lessons based on something like this,
> tn
> se
> stne
> ri
> ai
> ario
> arstneio
> gk
> gktn
> arstgkneio
> pl
> pltn
> uf
> ufse
> plfu
> plfutnse
> wy
> wyri
> q;
> q;ao
> wfpluy
> qwfpluy;
> bj
> bjgk
> qwfpbjluy;
> qwfpbjluy;arstgkneio
> dh
> dhtn
> c,
> c,se
> x.ri
> xcdh
> vm
> vmtn
> z/
> z/tn
> xcdvzmh
> xacrdsvtzgmkhneio
> qwfpbjluyarstgkneioxcdvzmh

It's for Colemak Mod-DH wide for ANSI, I want to practice 2 letters then next 2 and then combine them, then next two then combine them with previous letters and so on.
It is similar to the pattern used in [http://typingclub.com](http://typingclub.com)
I think you can count the number of characters if its less than 4 generate random sequence of letters or else generate some meaningful words.

**Comment by simgunz** [comment]
Makes sense. I'll implement it soon.

**Comment by simgunz** [comment]
Tested with:
```
python ../ktouch-lesson-generator.py  --exclude-previous-letters --previous-symbols-fraction=0 ../lessons/colemak.txt ../dictionaries/dict-en_uk.tx
```
most of the lessons have meaningless words, and few lessons have the same single word repeated.

With
```
python ../ktouch-lesson-generator.py  --exclude-previous-letters --previous-symbols-fraction=0 ../lessons/colemak.txt
```
the result seems better.
